export const G = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', 'Segoe UI', system-ui, sans-serif; }
  ::-webkit-scrollbar { width: 6px; height: 6px; }
  ::-webkit-scrollbar-track { background: #07101f; }
  ::-webkit-scrollbar-thumb { background: #1e3a5f; border-radius: 4px; }
  ::-webkit-scrollbar-thumb:hover { background: #2d5a8e; }
  input, select, textarea {
    font-family: inherit;
    background: #060e20;
    border: 1.5px solid #1e3a5f;
    border-radius: 6px;
    padding: 9px 12px;
    color: #e2e8f0;
    font-size: 13px;
    outline: none;
    width: 100%;
    transition: border-color 0.15s;
  }
  input:focus, select:focus, textarea:focus { border-color: #f59e0b; }
  select option { background: #0d1627; }
  textarea { resize: vertical; min-height: 80px; }
`;

export const ASSETS = [
  {
    id: 'A001',
    code: 'EQP-001',
    name: 'Compresor Atlas Copco GA55',
    area: 'Planta de Utilidades',
    status: 'activo',
    criticidad: 'alta',
    fabricante: 'Atlas Copco',
    modelo: 'GA55',
    serie: 'ATC-2021-001',
    instalacion: '2021-03-15',
  },
  {
    id: 'A002',
    code: 'EQP-002',
    name: 'Banda Transportadora #1',
    area: 'Linea de Empaque A',
    status: 'activo',
    criticidad: 'media',
    fabricante: 'Intralox',
    modelo: 'CT-500',
    serie: 'INT-2020-042',
    instalacion: '2020-06-20',
  },
  {
    id: 'A003',
    code: 'EQP-003',
    name: 'Caldera Cleaver Brooks 200BHP',
    area: 'Planta de Utilidades',
    status: 'mantenimiento',
    criticidad: 'alta',
    fabricante: 'Cleaver Brooks',
    modelo: '200BHP',
    serie: 'CB-2019-007',
    instalacion: '2019-11-01',
  },
  {
    id: 'A004',
    code: 'EQP-004',
    name: 'Torre de Enfriamiento Evapco',
    area: 'Planta de Utilidades',
    status: 'activo',
    criticidad: 'media',
    fabricante: 'Evapco',
    modelo: 'LSTE-24',
    serie: 'EVP-2022-003',
    instalacion: '2022-01-10',
  },
  {
    id: 'A005',
    code: 'EQP-005',
    name: 'Grua Puente 5T',
    area: 'Taller Central',
    status: 'detenido',
    criticidad: 'alta',
    fabricante: 'Demag',
    modelo: 'GP-5000',
    serie: 'DMG-2018-011',
    instalacion: '2018-05-22',
  },
  {
    id: 'A006',
    code: 'EQP-006',
    name: 'Selladora de Cajas Wexxar',
    area: 'Linea de Empaque A',
    status: 'activo',
    criticidad: 'baja',
    fabricante: 'Wexxar',
    modelo: 'SC-400',
    serie: 'WEX-2023-001',
    instalacion: '2023-02-14',
  },
  {
    id: 'A007',
    code: 'EQP-007',
    name: 'A/C Almacen Principal',
    area: 'Almacen Principal',
    status: 'activo',
    criticidad: 'baja',
    fabricante: 'Carrier',
    modelo: 'HVAC-5T',
    serie: 'CAR-2021-088',
    instalacion: '2021-08-30',
  },
];

export const PLANS = [
  {
    id: 'P001',
    assetId: 'A001',
    name: 'PM Semanal - Compresor GA55',
    freq: 1,
    unit: 'semanas',
    prioridad: 'alta',
    duracion: 2,
    activo: true,
    items: [
      'Verificar presion de aceite',
      'Revisar correas de transmision',
      'Limpiar filtros de aire',
      'Verificar temperatura de operacion',
    ],
  },
  {
    id: 'P002',
    assetId: 'A001',
    name: 'PM Mensual - Compresor GA55',
    freq: 1,
    unit: 'meses',
    prioridad: 'alta',
    duracion: 4,
    activo: true,
    items: [
      'Cambio de aceite',
      'Reemplazo de filtros',
      'Inspeccion general',
      'Revision valvulas de seguridad',
    ],
  },
  {
    id: 'P003',
    assetId: 'A002',
    name: 'PM Banda Transportadora',
    freq: 2,
    unit: 'semanas',
    prioridad: 'media',
    duracion: 1,
    activo: true,
    items: [
      'Lubricacion de rodillos',
      'Verificar tension de banda',
      'Inspeccion de alineacion',
    ],
  },
  {
    id: 'P004',
    assetId: 'A003',
    name: 'PM Mensual - Caldera 200BHP',
    freq: 1,
    unit: 'meses',
    prioridad: 'alta',
    duracion: 6,
    activo: true,
    items: [
      'Analisis de agua',
      'Purga de lodos',
      'Verificar quemador',
      'Controles de seguridad',
      'Inspeccion tuberia de vapor',
    ],
  },
  {
    id: 'P005',
    assetId: 'A004',
    name: 'PM Torre de Enfriamiento',
    freq: 1,
    unit: 'meses',
    prioridad: 'media',
    duracion: 3,
    activo: true,
    items: [
      'Limpieza de relleno',
      'Tratamiento de agua',
      'Verificar aspersores',
      'Inspeccion de motor ventilador',
    ],
  },
  {
    id: 'P006',
    assetId: 'A005',
    name: 'PM Anual - Grua Puente',
    freq: 1,
    unit: 'anios',
    prioridad: 'alta',
    duracion: 8,
    activo: false,
    items: [
      'Inspeccion estructural',
      'Revision de cables',
      'Prueba de carga nominal',
      'Calibracion de limites de carrera',
    ],
  },
];

export const INIT_WO = [
  {
    id: 'OT010',
    folio: 'OT-2025-011',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Pedro Sanchez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-10-05',
    fechaVen: '2025-10-05',
    fechaCierre: '2025-10-05',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT011',
    folio: 'OT-2025-012',
    tipo: 'preventivo',
    titulo: 'PM Rutina A004',
    assetId: 'A004',
    asignado: 'Luis Ramirez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-10-24',
    fechaVen: '2025-10-24',
    fechaCierre: '2025-10-24',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT012',
    folio: 'OT-2025-013',
    tipo: 'correctivo',
    titulo: 'Falla reportada A006',
    assetId: 'A006',
    asignado: 'Carlos Mendez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-10-23',
    fechaVen: '2025-10-23',
    fechaCierre: '2025-10-23',
    downtime: 197,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT013',
    folio: 'OT-2025-014',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Carlos Mendez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-10-12',
    fechaVen: '2025-10-12',
    fechaCierre: '2025-10-12',
    downtime: 244,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT014',
    folio: 'OT-2025-015',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-10-16',
    fechaVen: '2025-10-16',
    fechaCierre: '2025-10-16',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT015',
    folio: 'OT-2025-016',
    tipo: 'correctivo',
    titulo: 'Falla reportada A002',
    assetId: 'A002',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-10-02',
    fechaVen: '2025-10-02',
    fechaCierre: '2025-10-02',
    downtime: 159,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT016',
    folio: 'OT-2025-017',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'vencido',
    fechaCreacion: '2025-10-12',
    fechaVen: '2025-10-12',
    fechaCierre: null,
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT017',
    folio: 'OT-2025-018',
    tipo: 'correctivo',
    titulo: 'Falla reportada A003',
    assetId: 'A003',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-10-13',
    fechaVen: '2025-10-13',
    fechaCierre: '2025-10-13',
    downtime: 134,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT018',
    folio: 'OT-2025-019',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Luis Ramirez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-10-09',
    fechaVen: '2025-10-09',
    fechaCierre: '2025-10-09',
    downtime: 45,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT019',
    folio: 'OT-2025-020',
    tipo: 'correctivo',
    titulo: 'Falla reportada A003',
    assetId: 'A003',
    asignado: 'Carlos Mendez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-10-08',
    fechaVen: '2025-10-08',
    fechaCierre: '2025-10-08',
    downtime: 101,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT020',
    folio: 'OT-2025-021',
    tipo: 'correctivo',
    titulo: 'Falla reportada A002',
    assetId: 'A002',
    asignado: 'Luis Ramirez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-10-28',
    fechaVen: '2025-10-28',
    fechaCierre: '2025-10-28',
    downtime: 63,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT021',
    folio: 'OT-2025-022',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-10-04',
    fechaVen: '2025-10-04',
    fechaCierre: '2025-10-04',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT022',
    folio: 'OT-2025-023',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Luis Ramirez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-11-16',
    fechaVen: '2025-11-16',
    fechaCierre: '2025-11-16',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT023',
    folio: 'OT-2025-024',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Maria Gonzalez',
    prioridad: 'critico',
    status: 'cancelado',
    fechaCreacion: '2025-11-10',
    fechaVen: '2025-11-10',
    fechaCierre: null,
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT024',
    folio: 'OT-2025-025',
    tipo: 'preventivo',
    titulo: 'PM Rutina A004',
    assetId: 'A004',
    asignado: 'Luis Ramirez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-11-01',
    fechaVen: '2025-11-01',
    fechaCierre: '2025-11-01',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT025',
    folio: 'OT-2025-026',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Luis Ramirez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-11-21',
    fechaVen: '2025-11-21',
    fechaCierre: '2025-11-21',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT026',
    folio: 'OT-2025-027',
    tipo: 'preventivo',
    titulo: 'PM Rutina A006',
    assetId: 'A006',
    asignado: 'Luis Ramirez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-11-24',
    fechaVen: '2025-11-24',
    fechaCierre: '2025-11-24',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT027',
    folio: 'OT-2025-028',
    tipo: 'correctivo',
    titulo: 'Falla reportada A005',
    assetId: 'A005',
    asignado: 'Pedro Sanchez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-11-28',
    fechaVen: '2025-11-28',
    fechaCierre: '2025-11-28',
    downtime: 232,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT028',
    folio: 'OT-2025-029',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Luis Ramirez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-11-17',
    fechaVen: '2025-11-17',
    fechaCierre: '2025-11-17',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT029',
    folio: 'OT-2025-030',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-11-26',
    fechaVen: '2025-11-26',
    fechaCierre: '2025-11-26',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT030',
    folio: 'OT-2025-031',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-11-22',
    fechaVen: '2025-11-22',
    fechaCierre: '2025-11-22',
    downtime: 299,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT031',
    folio: 'OT-2025-032',
    tipo: 'correctivo',
    titulo: 'Falla reportada A007',
    assetId: 'A007',
    asignado: 'Maria Gonzalez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-11-22',
    fechaVen: '2025-11-22',
    fechaCierre: '2025-11-22',
    downtime: 133,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT032',
    folio: 'OT-2025-033',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-11-28',
    fechaVen: '2025-11-28',
    fechaCierre: '2025-11-28',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT033',
    folio: 'OT-2025-034',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Pedro Sanchez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-11-18',
    fechaVen: '2025-11-18',
    fechaCierre: '2025-11-18',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT034',
    folio: 'OT-2025-035',
    tipo: 'correctivo',
    titulo: 'Falla reportada A003',
    assetId: 'A003',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'cancelado',
    fechaCreacion: '2025-12-20',
    fechaVen: '2025-12-20',
    fechaCierre: null,
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT035',
    folio: 'OT-2025-036',
    tipo: 'correctivo',
    titulo: 'Falla reportada A005',
    assetId: 'A005',
    asignado: 'Maria Gonzalez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-12-14',
    fechaVen: '2025-12-14',
    fechaCierre: '2025-12-14',
    downtime: 273,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT036',
    folio: 'OT-2025-037',
    tipo: 'correctivo',
    titulo: 'Falla reportada A005',
    assetId: 'A005',
    asignado: 'Pedro Sanchez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-12-26',
    fechaVen: '2025-12-26',
    fechaCierre: '2025-12-26',
    downtime: 212,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT037',
    folio: 'OT-2025-038',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-12-11',
    fechaVen: '2025-12-11',
    fechaCierre: '2025-12-11',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT038',
    folio: 'OT-2025-039',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Luis Ramirez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2025-12-22',
    fechaVen: '2025-12-22',
    fechaCierre: '2025-12-22',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT039',
    folio: 'OT-2025-040',
    tipo: 'correctivo',
    titulo: 'Falla reportada A001',
    assetId: 'A001',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-12-18',
    fechaVen: '2025-12-18',
    fechaCierre: '2025-12-18',
    downtime: 105,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT040',
    folio: 'OT-2025-041',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-12-27',
    fechaVen: '2025-12-27',
    fechaCierre: '2025-12-27',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT041',
    folio: 'OT-2025-042',
    tipo: 'correctivo',
    titulo: 'Falla reportada A003',
    assetId: 'A003',
    asignado: 'Carlos Mendez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-12-19',
    fechaVen: '2025-12-19',
    fechaCierre: '2025-12-19',
    downtime: 154,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT042',
    folio: 'OT-2025-043',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2025-12-21',
    fechaVen: '2025-12-21',
    fechaCierre: '2025-12-21',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT043',
    folio: 'OT-2025-044',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Pedro Sanchez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-12-02',
    fechaVen: '2025-12-02',
    fechaCierre: '2025-12-02',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT044',
    folio: 'OT-2025-045',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Pedro Sanchez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2025-12-26',
    fechaVen: '2025-12-26',
    fechaCierre: '2025-12-26',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT045',
    folio: 'OT-2025-046',
    tipo: 'correctivo',
    titulo: 'Falla reportada A002',
    assetId: 'A002',
    asignado: 'Pedro Sanchez',
    prioridad: 'media',
    status: 'completado',
    fechaCreacion: '2025-12-10',
    fechaVen: '2025-12-10',
    fechaCierre: '2025-12-10',
    downtime: 150,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT046',
    folio: 'OT-2026-047',
    tipo: 'preventivo',
    titulo: 'PM Rutina A006',
    assetId: 'A006',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-17',
    fechaVen: '2026-01-17',
    fechaCierre: '2026-01-17',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT047',
    folio: 'OT-2026-048',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Carlos Mendez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-26',
    fechaVen: '2026-01-26',
    fechaCierre: '2026-01-26',
    downtime: 143,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT048',
    folio: 'OT-2026-049',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-01-14',
    fechaVen: '2026-01-14',
    fechaCierre: '2026-01-14',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT049',
    folio: 'OT-2026-050',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-01-11',
    fechaVen: '2026-01-11',
    fechaCierre: '2026-01-11',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT050',
    folio: 'OT-2026-051',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Luis Ramirez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2026-01-15',
    fechaVen: '2026-01-15',
    fechaCierre: '2026-01-15',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT051',
    folio: 'OT-2026-052',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-02',
    fechaVen: '2026-01-02',
    fechaCierre: '2026-01-02',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT052',
    folio: 'OT-2026-053',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-21',
    fechaVen: '2026-01-21',
    fechaCierre: '2026-01-21',
    downtime: 96,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT053',
    folio: 'OT-2026-054',
    tipo: 'correctivo',
    titulo: 'Falla reportada A005',
    assetId: 'A005',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-01-12',
    fechaVen: '2026-01-12',
    fechaCierre: '2026-01-12',
    downtime: 60,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT054',
    folio: 'OT-2026-055',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-09',
    fechaVen: '2026-01-09',
    fechaCierre: '2026-01-09',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT055',
    folio: 'OT-2026-056',
    tipo: 'correctivo',
    titulo: 'Falla reportada A005',
    assetId: 'A005',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-01-19',
    fechaVen: '2026-01-19',
    fechaCierre: '2026-01-19',
    downtime: 272,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT056',
    folio: 'OT-2026-057',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Pedro Sanchez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2026-01-27',
    fechaVen: '2026-01-27',
    fechaCierre: '2026-01-27',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT057',
    folio: 'OT-2026-058',
    tipo: 'preventivo',
    titulo: 'PM Rutina A001',
    assetId: 'A001',
    asignado: 'Maria Gonzalez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2026-01-05',
    fechaVen: '2026-01-05',
    fechaCierre: '2026-01-05',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT058',
    folio: 'OT-2026-059',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-02-14',
    fechaVen: '2026-02-14',
    fechaCierre: '2026-02-14',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT059',
    folio: 'OT-2026-060',
    tipo: 'preventivo',
    titulo: 'PM Rutina A003',
    assetId: 'A003',
    asignado: 'Maria Gonzalez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2026-02-04',
    fechaVen: '2026-02-04',
    fechaCierre: '2026-02-04',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT060',
    folio: 'OT-2026-061',
    tipo: 'correctivo',
    titulo: 'Falla reportada A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-02-07',
    fechaVen: '2026-02-07',
    fechaCierre: '2026-02-07',
    downtime: 80,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT061',
    folio: 'OT-2026-062',
    tipo: 'correctivo',
    titulo: 'Falla reportada A007',
    assetId: 'A007',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-02-08',
    fechaVen: '2026-02-08',
    fechaCierre: '2026-02-08',
    downtime: 279,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT062',
    folio: 'OT-2026-063',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-02-08',
    fechaVen: '2026-02-08',
    fechaCierre: '2026-02-08',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT063',
    folio: 'OT-2026-064',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-02-14',
    fechaVen: '2026-02-14',
    fechaCierre: '2026-02-14',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT064',
    folio: 'OT-2026-065',
    tipo: 'correctivo',
    titulo: 'Falla reportada A004',
    assetId: 'A004',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-02-19',
    fechaVen: '2026-02-19',
    fechaCierre: '2026-02-19',
    downtime: 212,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT065',
    folio: 'OT-2026-066',
    tipo: 'correctivo',
    titulo: 'Falla reportada A003',
    assetId: 'A003',
    asignado: 'Pedro Sanchez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-02-06',
    fechaVen: '2026-02-06',
    fechaCierre: '2026-02-06',
    downtime: 96,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT066',
    folio: 'OT-2026-067',
    tipo: 'preventivo',
    titulo: 'PM Rutina A005',
    assetId: 'A005',
    asignado: 'Carlos Mendez',
    prioridad: 'critico',
    status: 'vencido',
    fechaCreacion: '2026-02-08',
    fechaVen: '2026-02-08',
    fechaCierre: null,
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT067',
    folio: 'OT-2026-068',
    tipo: 'correctivo',
    titulo: 'Falla reportada A006',
    assetId: 'A006',
    asignado: 'Maria Gonzalez',
    prioridad: 'baja',
    status: 'completado',
    fechaCreacion: '2026-02-11',
    fechaVen: '2026-02-11',
    fechaCierre: '2026-02-11',
    downtime: 145,
    obs: 'Generado por simulacion.',
    causa: 'Desgaste natural',
    accion: 'Reparacion efectuada',
  },
  {
    id: 'OT068',
    folio: 'OT-2026-069',
    tipo: 'preventivo',
    titulo: 'PM Rutina A002',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-02-02',
    fechaVen: '2026-02-02',
    fechaCierre: '2026-02-02',
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT069',
    folio: 'OT-2026-070',
    tipo: 'preventivo',
    titulo: 'PM Rutina A006',
    assetId: 'A006',
    asignado: 'Pedro Sanchez',
    prioridad: 'baja',
    status: 'vencido',
    fechaCreacion: '2026-02-23',
    fechaVen: '2026-02-23',
    fechaCierre: null,
    downtime: 0,
    obs: 'Generado por simulacion.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT070',
    folio: 'OT-2026-071',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A002',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-03-01',
    fechaVen: '2026-03-01',
    fechaCierre: '2026-03-01',
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT071',
    folio: 'OT-2026-072',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A003',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-03-02',
    fechaVen: '2026-03-02',
    fechaCierre: '2026-03-02',
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT072',
    folio: 'OT-2026-073',
    tipo: 'correctivo',
    titulo: 'Averia urgente',
    assetId: 'A004',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'completado',
    fechaCreacion: '2026-03-03',
    fechaVen: '2026-03-03',
    fechaCierre: '2026-03-03',
    downtime: 120,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT073',
    folio: 'OT-2026-074',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A005',
    asignado: 'Carlos Mendez',
    prioridad: 'critico',
    status: 'completado',
    fechaCreacion: '2026-03-04',
    fechaVen: '2026-03-04',
    fechaCierre: '2026-03-04',
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT074',
    folio: 'OT-2026-075',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A006',
    asignado: 'Luis Ramirez',
    prioridad: 'alta',
    status: 'pendiente',
    fechaCreacion: '2026-03-05',
    fechaVen: '2026-03-05',
    fechaCierre: null,
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT075',
    folio: 'OT-2026-076',
    tipo: 'correctivo',
    titulo: 'Averia urgente',
    assetId: 'A007',
    asignado: 'Maria Gonzalez',
    prioridad: 'alta',
    status: 'pendiente',
    fechaCreacion: '2026-03-06',
    fechaVen: '2026-03-06',
    fechaCierre: null,
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT076',
    folio: 'OT-2026-077',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A001',
    asignado: 'Pedro Sanchez',
    prioridad: 'alta',
    status: 'pendiente',
    fechaCreacion: '2026-03-07',
    fechaVen: '2026-03-07',
    fechaCierre: null,
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
  {
    id: 'OT077',
    folio: 'OT-2026-078',
    tipo: 'preventivo',
    titulo: 'Inspeccion Marzo',
    assetId: 'A002',
    asignado: 'Carlos Mendez',
    prioridad: 'critico',
    status: 'pendiente',
    fechaCreacion: '2026-03-08',
    fechaVen: '2026-03-08',
    fechaCierre: null,
    downtime: 0,
    obs: 'Datos de marzo.',
    causa: null,
    accion: null,
  },
];

export const INIT_NOTIFS = [
  {
    id: 'N1',
    tipo: 'vencida',
    titulo: 'OT Vencida: PM Torre de Enfriamiento',
    msg: 'La orden OT-2026-004 vencio el 1 de marzo sin completarse.',
    fecha: '2026-03-02',
    leida: false,
  },
  {
    id: 'N2',
    tipo: 'proxima',
    titulo: 'PM proximo: Compresor GA55',
    msg: 'El plan PM Semanal Compresor vence el 8 de marzo.',
    fecha: '2026-03-06',
    leida: false,
  },
  {
    id: 'N3',
    tipo: 'asignada',
    titulo: 'Nueva asignacion: OT-2026-005',
    msg: 'OT-2026-005 Falla electrica Grua Puente asignada a Pedro Sanchez.',
    fecha: '2026-03-06',
    leida: false,
  },
  {
    id: 'N4',
    tipo: 'proxima',
    titulo: 'PM proximo: Caldera  Mensual',
    msg: 'El plan PM Caldera Mensual vence hoy 7 de marzo.',
    fecha: '2026-03-07',
    leida: true,
  },
  {
    id: 'N5',
    tipo: 'vencida',
    titulo: 'OT Vencida: Falla rodamiento Banda #1',
    msg: 'La orden OT-2026-002 vencio sin cerrarse.',
    fecha: '2026-03-06',
    leida: true,
  },
];

export const complianceData = [
  { mes: 'Oct', val: 82 },
  { mes: 'Nov', val: 78 },
  { mes: 'Dic', val: 85 },
  { mes: 'Ene', val: 88 },
  { mes: 'Feb', val: 75 },
  { mes: 'Mar', val: 68 },
];
export const downtimeData = [
  { mes: 'Oct', hrs: 8 },
  { mes: 'Nov', hrs: 12 },
  { mes: 'Dic', hrs: 5 },
  { mes: 'Ene', hrs: 15 },
  { mes: 'Feb', hrs: 9 },
  { mes: 'Mar', hrs: 7 },
];
export const tipoData = [
  { name: 'Preventivo', value: 14, color: '#3b82f6' },
  { name: 'Correctivo', value: 8, color: '#ef4444' },
];
export const topFallas = [
  { asset: 'Grua Puente 5T', count: 4, down: 18 },
  { asset: 'Banda Transportadora #1', count: 3, down: 12 },
  { asset: 'Compresor GA55', count: 2, down: 4 },
  { asset: 'A/C Almacen', count: 2, down: 3 },
  { asset: 'Caldera 200BHP', count: 1, down: 6 },
];

export const assetComplianceData = {
  A001: [
    { mes: 'Oct', val: 85 },
    { mes: 'Nov', val: 90 },
    { mes: 'Dic', val: 88 },
    { mes: 'Ene', val: 92 },
    { mes: 'Feb', val: 85 },
    { mes: 'Mar', val: 80 },
  ],
  A002: [
    { mes: 'Oct', val: 70 },
    { mes: 'Nov', val: 65 },
    { mes: 'Dic', val: 75 },
    { mes: 'Ene', val: 80 },
    { mes: 'Feb', val: 60 },
    { mes: 'Mar', val: 55 },
  ],
  A003: [
    { mes: 'Oct', val: 90 },
    { mes: 'Nov', val: 85 },
    { mes: 'Dic', val: 95 },
    { mes: 'Ene', val: 88 },
    { mes: 'Feb', val: 75 },
    { mes: 'Mar', val: 70 },
  ],
  A004: [
    { mes: 'Oct', val: 78 },
    { mes: 'Nov', val: 82 },
    { mes: 'Dic', val: 85 },
    { mes: 'Ene', val: 90 },
    { mes: 'Feb', val: 78 },
    { mes: 'Mar', val: 72 },
  ],
  A005: [
    { mes: 'Oct', val: 50 },
    { mes: 'Nov', val: 45 },
    { mes: 'Dic', val: 40 },
    { mes: 'Ene', val: 55 },
    { mes: 'Feb', val: 30 },
    { mes: 'Mar', val: 25 },
  ],
  A006: [
    { mes: 'Oct', val: 95 },
    { mes: 'Nov', val: 92 },
    { mes: 'Dic', val: 98 },
    { mes: 'Ene', val: 94 },
    { mes: 'Feb', val: 90 },
    { mes: 'Mar', val: 88 },
  ],
  A007: [
    { mes: 'Oct', val: 88 },
    { mes: 'Nov', val: 85 },
    { mes: 'Dic', val: 90 },
    { mes: 'Ene', val: 92 },
    { mes: 'Feb', val: 80 },
    { mes: 'Mar', val: 75 },
  ],
};

export const assetDowntimeData = {
  A001: [
    { mes: 'Oct', hrs: 2 },
    { mes: 'Nov', hrs: 1 },
    { mes: 'Dic', hrs: 3 },
    { mes: 'Ene', hrs: 1.5 },
    { mes: 'Feb', hrs: 2 },
    { mes: 'Mar', hrs: 3 },
  ],
  A002: [
    { mes: 'Oct', hrs: 5 },
    { mes: 'Nov', hrs: 8 },
    { mes: 'Dic', hrs: 4 },
    { mes: 'Ene', hrs: 6 },
    { mes: 'Feb', hrs: 12 },
    { mes: 'Mar', hrs: 15 },
  ],
  A003: [
    { mes: 'Oct', hrs: 1 },
    { mes: 'Nov', hrs: 2 },
    { mes: 'Dic', hrs: 0.5 },
    { mes: 'Ene', hrs: 1 },
    { mes: 'Feb', hrs: 4 },
    { mes: 'Mar', hrs: 5 },
  ],
  A004: [
    { mes: 'Oct', hrs: 3 },
    { mes: 'Nov', hrs: 2 },
    { mes: 'Dic', hrs: 1.5 },
    { mes: 'Ene', hrs: 1 },
    { mes: 'Feb', hrs: 3 },
    { mes: 'Mar', hrs: 4 },
  ],
  A005: [
    { mes: 'Oct', hrs: 15 },
    { mes: 'Nov', hrs: 18 },
    { mes: 'Dic', hrs: 20 },
    { mes: 'Ene', hrs: 12 },
    { mes: 'Feb', hrs: 25 },
    { mes: 'Mar', hrs: 30 },
  ],
  A006: [
    { mes: 'Oct', hrs: 0.5 },
    { mes: 'Nov', hrs: 1 },
    { mes: 'Dic', hrs: 0.2 },
    { mes: 'Ene', hrs: 1 },
    { mes: 'Feb', hrs: 1.5 },
    { mes: 'Mar', hrs: 2 },
  ],
  A007: [
    { mes: 'Oct', hrs: 2 },
    { mes: 'Nov', hrs: 3 },
    { mes: 'Dic', hrs: 1.5 },
    { mes: 'Ene', hrs: 1 },
    { mes: 'Feb', hrs: 4 },
    { mes: 'Mar', hrs: 5 },
  ],
};

export const assetTipoData = {
  A001: [
    { name: 'Preventivo', value: 8, color: '#3b82f6' },
    { name: 'Correctivo', value: 2, color: '#ef4444' },
  ],
  A002: [
    { name: 'Preventivo', value: 3, color: '#3b82f6' },
    { name: 'Correctivo', value: 5, color: '#ef4444' },
  ],
  A003: [
    { name: 'Preventivo', value: 5, color: '#3b82f6' },
    { name: 'Correctivo', value: 1, color: '#ef4444' },
  ],
  A004: [
    { name: 'Preventivo', value: 4, color: '#3b82f6' },
    { name: 'Correctivo', value: 1, color: '#ef4444' },
  ],
  A005: [
    { name: 'Preventivo', value: 1, color: '#3b82f6' },
    { name: 'Correctivo', value: 6, color: '#ef4444' },
  ],
  A006: [
    { name: 'Preventivo', value: 6, color: '#3b82f6' },
    { name: 'Correctivo', value: 0, color: '#ef4444' },
  ],
  A007: [
    { name: 'Preventivo', value: 2, color: '#3b82f6' },
    { name: 'Correctivo', value: 2, color: '#ef4444' },
  ],
};

export const STC = {
  activo: '#22c55e',
  detenido: '#ef4444',
  mantenimiento: '#f59e0b',
  descomisionado: '#64748b',
  pendiente: '#94a3b8',
  asignado: '#3b82f6',
  en_progreso: '#f59e0b',
  pausado: '#f97316',
  completado: '#22c55e',
  cancelado: '#64748b',
  vencido: '#ef4444',
};
export const STL = {
  activo: 'Activo',
  detenido: 'Detenido',
  mantenimiento: 'En Mantenimiento',
  descomisionado: 'Descomisionado',
  pendiente: 'Pendiente',
  asignado: 'Asignado',
  en_progreso: 'En Progreso',
  pausado: 'Pausado',
  completado: 'Completado',
  cancelado: 'Cancelado',
  vencido: 'Vencido',
};
export const PRC = {
  baja: '#22c55e',
  media: '#3b82f6',
  alta: '#f59e0b',
  critico: '#ef4444',
};
export const PRL = {
  baja: 'Baja',
  media: 'Media',
  alta: 'Alta',
  critico: 'Critico',
};
export const CRC = { baja: '#22c55e', media: '#f59e0b', alta: '#ef4444' };
export const NTC = {
  vencida: '#ef4444',
  proxima: '#f59e0b',
  asignada: '#3b82f6',
};
export const NTL = {
  vencida: 'Vencida',
  proxima: 'Proxima',
  asignada: 'Asignada',
};
export const NTI = { vencida: '⚠', proxima: '🔔', asignada: '📋' };
export const TT = {
  background: '#0d1627',
  border: '1px solid #1e3a5f',
  borderRadius: 6,
  fontSize: 12,
  color: '#e2e8f0',
};

// ─── INSPECCIONES ────────────────────────────────────────────────────────────────
export const TURNOS = ['Matutino', 'Vespertino', 'Nocturno'];

export const CHECKLIST_ESTADOS = {
  pendiente: 'Pendiente',
  en_ejecucion: 'En Ejecucion',
  completado: 'Completado',
  vencido: 'Vencido',
};

export const CHECKLIST_ESTADO_COLORES = {
  pendiente: '#94a3b8',
  en_ejecucion: '#f59e0b',
  completado: '#22c55e',
  vencido: '#ef4444',
};

export const HALLAZGO_STATUS = {
  abierto: 'Abierto',
  en_proceso: 'En Proceso',
  resuelto: 'Resuelto',
};

export const HALLAZGO_COLORES = {
  abierto: '#ef4444',
  en_proceso: '#f59e0b',
  resuelto: '#22c55e',
};

export const SEVERIDADES = {
  baja: 'Baja',
  media: 'Media',
  alta: 'Alta',
  critica: 'Critica',
};

export const SEVERIDAD_COLORES = {
  baja: '#22c55e',
  media: '#3b82f6',
  alta: '#f59e0b',
  critica: '#ef4444',
};

export const ITEM_VALORES = {
  ok: 'OK',
  nok: 'No OK',
  na: 'N/A',
};

export const ITEM_VALOR_COLORES = {
  ok: '#22c55e',
  nok: '#ef4444',
  na: '#64748b',
};

export const CHECKLIST_ITEMS_DEFAULT = [
  { id: 1, descripcion: 'Limpieza general' },
  { id: 2, descripcion: 'Fugas de aire' },
  { id: 3, descripcion: 'Fugas de aceite' },
  { id: 4, descripcion: 'Ruidos anormales' },
  { id: 5, descripcion: 'Vibración anormal' },
  { id: 6, descripcion: 'Temperatura normal' },
  { id: 7, descripcion: 'Guardas colocadas' },
  { id: 8, descripcion: 'Sensores limpios' },
  { id: 9, descripcion: 'Cableado visible en buen estado' },
  { id: 10, descripcion: 'Presión correcta' },
  { id: 11, descripcion: 'Lubricación visible adecuada' },
  { id: 12, descripcion: 'Tornillería sin aflojamientos' },
  { id: 13, descripcion: 'Paros o alarmas recientes' },
  { id: 14, descripcion: 'Nivel de fluidos correcto' },
];

export const PLANTILLAS_CHECKLIST = [
  {
    id: 'PL001',
    nombre: 'Inspeccion General - Compresor',
    activoId: 'A001',
    activoCode: 'EQP-001',
    activoName: 'Compresor Atlas Copco GA55',
    items: [
      { id: 1, descripcion: 'Limpieza general' },
      { id: 2, descripcion: 'Fugas de aire' },
      { id: 3, descripcion: 'Fugas de aceite' },
      { id: 4, descripcion: 'Ruidos anormales' },
      { id: 5, descripcion: 'Vibración anormal' },
      { id: 6, descripcion: 'Temperatura normal' },
      { id: 7, descripcion: 'Guardas colocadas' },
      { id: 8, descripcion: 'Sensores limpios' },
      { id: 9, descripcion: 'Cableado visible en buen estado' },
      { id: 10, descripcion: 'Presión correcta' },
      { id: 11, descripcion: 'Lubricación visible adecuada' },
      { id: 12, descripcion: 'Tornillería sin aflojamientos' },
      { id: 13, descripcion: 'Paros o alarmas recientes' },
      { id: 14, descripcion: 'Nivel de aceite' },
    ],
  },
  {
    id: 'PL002',
    nombre: 'Inspeccion General - Banda Transportadora',
    activoId: 'A002',
    activoCode: 'EQP-002',
    activoName: 'Banda Transportadora #1',
    items: [
      { id: 1, descripcion: 'Limpieza general' },
      { id: 2, descripcion: 'Tension de banda adecuada' },
      { id: 3, descripcion: 'Rodillos sin desgaste' },
      { id: 4, descripcion: 'Ruidos anormales' },
      { id: 5, descripcion: 'Vibración anormal' },
      { id: 6, descripcion: 'Temperatura normal motor' },
      { id: 7, descripcion: 'Guardas colocadas' },
      { id: 8, descripcion: 'Sensores de posicion' },
      { id: 9, descripcion: 'Cableado en buen estado' },
      { id: 10, descripcion: 'Lubricacion de rodillos' },
      { id: 11, descripcion: 'Alineacion correcta' },
      { id: 12, descripcion: 'Tornilleria ajustada' },
      { id: 13, descripcion: 'Paros o alarmas recientes' },
      { id: 14, descripcion: 'Estado de sensores' },
    ],
  },
  {
    id: 'PL003',
    nombre: 'Inspeccion General - Caldera',
    activoId: 'A003',
    activoCode: 'EQP-003',
    activoName: 'Caldera Cleaver Brooks 200BHP',
    items: [
      { id: 1, descripcion: 'Limpieza general' },
      { id: 2, descripcion: 'Nivel de agua en norma' },
      { id: 3, descripcion: 'Presion de trabajo' },
      { id: 4, descripcion: 'Quemador operando normal' },
      { id: 5, descripcion: 'Valvulas de seguridad' },
      { id: 6, descripcion: 'Temperatura normal' },
      { id: 7, descripcion: 'Guardas de proteccion' },
      { id: 8, descripcion: 'Controles de seguridad' },
      { id: 9, descripcion: 'Tuberia sin fugas' },
      { id: 10, descripcion: 'Purga de lodos' },
      { id: 11, descripcion: 'Tratamiento de agua' },
      { id: 12, descripcion: 'Tornilleria apretada' },
      { id: 13, descripcion: 'Alarmas recientes' },
      { id: 14, descripcion: 'Registro de presiones' },
    ],
  },
];

export const INIT_CHECKLISTS = [
  {
    id: 'CHK001',
    folio: 'CHK-2026-001',
    plantillaId: 'PL001',
    plantillaName: 'Inspeccion General - Compresor',
    activoId: 'A001',
    activoCode: 'EQP-001',
    activoName: 'Compresor Atlas Copco GA55',
    area: 'Planta de Utilidades',
    fecha: '2026-03-09',
    turno: 'Matutino',
    responsable: 'Carlos Mendez',
    horometro: 1250,
    estado: 'completado',
    items: [
      { itemId: 1, valor: 'ok', nota: '' },
      { itemId: 2, valor: 'ok', nota: '' },
      { itemId: 3, valor: 'ok', nota: '' },
      { itemId: 4, valor: 'ok', nota: '' },
      { itemId: 5, valor: 'ok', nota: '' },
      { itemId: 6, valor: 'ok', nota: '' },
      { itemId: 7, valor: 'ok', nota: '' },
      { itemId: 8, valor: 'ok', nota: '' },
      { itemId: 9, valor: 'ok', nota: '' },
      { itemId: 10, valor: 'ok', nota: '' },
      { itemId: 11, valor: 'ok', nota: '' },
      { itemId: 12, valor: 'ok', nota: '' },
      { itemId: 13, valor: 'ok', nota: '' },
      { itemId: 14, valor: 'ok', nota: '' },
    ],
    createdAt: '2026-03-09T08:00:00',
  },
  {
    id: 'CHK002',
    folio: 'CHK-2026-002',
    plantillaId: 'PL002',
    plantillaName: 'Inspeccion General - Banda Transportadora',
    activoId: 'A002',
    activoCode: 'EQP-002',
    activoName: 'Banda Transportadora #1',
    area: 'Linea de Empaque A',
    fecha: '2026-03-09',
    turno: 'Matutino',
    responsable: 'Luis Ramirez',
    horometro: 850,
    estado: 'completado',
    items: [
      { itemId: 1, valor: 'ok', nota: '' },
      { itemId: 2, valor: 'ok', nota: '' },
      {
        itemId: 3,
        valor: 'nok',
        nota: 'Rodillo central con desgaste excesivo',
      },
      { itemId: 4, valor: 'ok', nota: '' },
      { itemId: 5, valor: 'ok', nota: '' },
      { itemId: 6, valor: 'ok', nota: '' },
      { itemId: 7, valor: 'ok', nota: '' },
      { itemId: 8, valor: 'ok', nota: '' },
      { itemId: 9, valor: 'ok', nota: '' },
      { itemId: 10, valor: 'na', nota: '' },
      { itemId: 11, valor: 'ok', nota: '' },
      { itemId: 12, valor: 'ok', nota: '' },
      { itemId: 13, valor: 'ok', nota: '' },
      { itemId: 14, valor: 'ok', nota: '' },
    ],
    createdAt: '2026-03-09T09:30:00',
  },
  {
    id: 'CHK003',
    folio: 'CHK-2026-003',
    plantillaId: 'PL001',
    plantillaName: 'Inspeccion General - Compresor',
    activoId: 'A001',
    activoCode: 'EQP-001',
    activoName: 'Compresor Atlas Copco GA55',
    area: 'Planta de Utilidades',
    fecha: '2026-03-10',
    turno: 'Matutino',
    responsable: 'Carlos Mendez',
    horometro: 1260,
    estado: 'pendiente',
    items: [],
    createdAt: '2026-03-10T07:00:00',
  },
  {
    id: 'CHK004',
    folio: 'CHK-2026-004',
    plantillaId: 'PL003',
    plantillaName: 'Inspeccion General - Caldera',
    activoId: 'A003',
    activoCode: 'EQP-003',
    activoName: 'Caldera Cleaver Brooks 200BHP',
    area: 'Planta de Utilidades',
    fecha: '2026-03-08',
    turno: 'Matutino',
    responsable: 'Maria Gonzalez',
    horometro: 2100,
    estado: 'vencido',
    items: [],
    createdAt: '2026-03-08T08:00:00',
  },
  {
    id: 'CHK005',
    folio: 'CHK-2026-005',
    plantillaId: 'PL002',
    plantillaName: 'Inspeccion General - Banda Transportadora',
    activoId: 'A002',
    activoCode: 'EQP-002',
    activoName: 'Banda Transportadora #1',
    area: 'Linea de Empaque A',
    fecha: '2026-03-10',
    turno: 'Vespertino',
    responsable: 'Pedro Sanchez',
    horometro: 860,
    estado: 'pendiente',
    items: [],
    createdAt: '2026-03-10T14:00:00',
  },
];

export const INIT_HALLAZGOS = [
  {
    id: 'H001',
    checklistId: 'CHK002',
    checklistFolio: 'CHK-2026-002',
    itemId: 3,
    itemDescripcion: 'Rodillos con desgaste excesivo',
    descripcion:
      'Rodillo central presenta desgaste excesivo en la banda, requiere reemplazo',
    severidad: 'alta',
    status: 'abierto',
    activoId: 'A002',
    activoCode: 'EQP-002',
    activoName: 'Banda Transportadora #1',
    responsable: 'Luis Ramirez',
    createdAt: '2026-03-09T09:35:00',
    otId: null,
    resolvedAt: null,
  },
  {
    id: 'H002',
    checklistId: 'CHK001',
    checklistFolio: 'CHK-2026-001',
    itemId: 10,
    itemDescripcion: 'Presión correcta',
    descripcion: 'Presión ligeramente baja, ajustar regulacion',
    severidad: 'media',
    status: 'resuelto',
    activoId: 'A001',
    activoCode: 'EQP-001',
    activoName: 'Compresor Atlas Copco GA55',
    responsable: 'Carlos Mendez',
    createdAt: '2026-03-09T08:15:00',
    otId: null,
    resolvedAt: '2026-03-09T10:00:00',
  },
];
